<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <UseWPF>true</UseWPF>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
    <WarningsAsErrors>$(WarningsAsErrors);xUnit1051</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <ProjectReference Include="../../src/MhwModManager.Core/MhwModManager.Core.csproj" />
    <ProjectReference Include="../../src/MhwModManager.Storage/MhwModManager.Storage.csproj" />
    <ProjectReference Include="../../src/MhwModManager.Filesystem/MhwModManager.Filesystem.csproj" />
    <ProjectReference Include="../../src/MhwModManager.Diagnostics/MhwModManager.Diagnostics.csproj" />
    <ProjectReference Include="../../src/MhwModManager.App/MhwModManager.App.csproj" />
    <ProjectReference Include="../../src/MhwModManager.Updater/MhwModManager.Updater.csproj" />
    <ProjectReference Include="../../src/MhwModManager.Updater.Helper/MhwModManager.Updater.Helper.csproj"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="../MhwModManager.FunctionVerifier/MhwModManager.FunctionVerifier.csproj" />
  </ItemGroup>
</Project>
