<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <AssemblyName>MHW Mod Manager Updater</AssemblyName>
    <RootNamespace>MhwModManager.Updater.Helper</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MhwModManager.Updater/MhwModManager.Updater.csproj" />
    <ProjectReference Include="../MhwModManager.Core/MhwModManager.Core.csproj" />
  </ItemGroup>
</Project>